config/routes.rb
Rails.application.routes.draw do

  root 'orders#index'
  resources :orders, only: [:index]
  resources :clients, :sellers, except: [:destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  
  has_many :orders
  has_many :sellers, through: :orders

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :seller
  belongs_to :client

end

app/models/seller.rb
class Seller < ApplicationRecord

  has_many :orders
  has_many :clients, through: :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :find_client, only: [:edit, :update]
  before_action :client, only: [:new]

  def index
    @clients = Client.all
  end

  def new
  end

  def create
    @client = Client.new(name: params[:client][:name], seller_ids: params[:client][:seller_ids])
    if @client.save
      redirect_to clients_path
    else 
      render :new
    end
  end

  def edit
  end

  def update
    redirect_to clients_path if @client.update(name: params[:client][:name], seller_ids: params[:client][:seller_ids])
  end

  private 

  def find_client
    @client = Client.find(params[:id])
  end

  def client
    @client ||= Client.new
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

  before_action :find_seller, only: [:edit, :update]
  before_action :seller, only: [:new]

  def index
    @sellers = Seller.all
  end

  def new
  end

  def create
    @seller = Seller.new(name: params[:client][:name], seller_ids: params[:client][:seller_ids])
    if @seller.save
      redirect_to sellers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    redirect_to sellers_path if @seller.update(name: params[:client][:name], seller_ids: params[:client][:seller_ids])
  end

  private

  def find_seller
    @seller = Seller.find(params[:id])
  end

  def seller_params
    params.require(:post).permit(:name, :seller_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/clients/_form.haml
= form_for @client do |f|
  %p
    = f.label(:name)
    = f.text_field(:name)
  %p
    = f.label(:seller_ids)
    = f.collection_check_boxes(:seller_ids, Seller.all,:id,:name)
  %p
    = f.submit

app/views/clients/edit.haml
%h5 
  Edit client data
= render 'form' 

app/views/clients/index.haml
%h4 
  Clients list
%table
  %thead
    %tr
      %th Id
      %th Name
      %th Sellers
  %tbody
    - @clients.each do |client|
      %tr
        %td 
          = client.id
        %td 
          = client.name
        %td
          - client.sellers.each do |seller|
            = link_to "#{seller.name} ", edit_seller_path(id: seller.id)
        %td 
          = link_to 'Edit', edit_client_path(id: client.id)
%p
  = link_to 'Back', root_path
  = link_to 'New Client', new_client_path 

app/views/clients/new.haml
%h5 
  New client
= render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HmT</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.haml
%h4 
  Orders list
%table
  %thead
    %tr
      %th Id
      %th Seller
      %th Client
  %tbody
    - @orders.each do |order|
      %tr
        %td 
          = order.id
        %td 
          = link_to order.seller.name, edit_seller_path(id: order.seller.id)
        %td 
          = link_to order.client.name, edit_client_path(id: order.client.id)
%p 
  = link_to "Clients list", clients_path
  = link_to "Sellers list", sellers_path

app/views/sellers/_form.haml
= form_for @seller do |f|
  %p
    = f.label(:name)
    = f.text_field(:name)
  %p
    = f.label(:client_ids)
    = f.collection_check_boxes(:client_ids, Client.all,:id,:name)
  %p
    = f.submit

app/views/sellers/edit.haml
%h5 
  Edit seller data
= render 'form' 

app/views/sellers/index.haml
%h4 
  Sellers list
%table
  %thead
    %tr
      %th Id
      %th Name
      %th Clients
  %tbody
    - @sellers.each do |seller|
      %tr
        %td 
          = seller.id
        %td 
          = seller.name
        %td
          - seller.clients.each do |client|
            = link_to "#{client.name} ", edit_client_path(id: client.id)
        %td 
          = link_to 'Edit', edit_seller_path(id: seller.id)
%p
  = link_to 'Back', root_path
  = link_to 'New Seller', new_seller_path 

app/views/sellers/new.haml
%h5 
  New Seller
= render 'form'